name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发条件：当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      - name: Checkout repository  # 检出代码库
        uses: actions/checkout@v3

      - name: Set up Node.js  # 设置 Node.js 环境
        uses: actions/setup-node@v3
       

      - name: Install dependencies  # 安装依赖
        run: npm install

      - name: Build project  # 构建项目
        run: npm run build

      - name: List files in dist directory  # 调试步骤：列出 dist 目录中的文件
        run: ls -la dist || echo "dist directory not found"

      - name: Deploy to GitHub Pages  # 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_PAT }}  # 使用个人访问令牌
          publish_dir: ./dist  # 发布目录为 dist
